POST http://localhost:5000/post
Content-Type: application/json

{
    "title": "hello i am guy",
    "body": "fuck you lol",
    "subject": "fuck you again",
    "date": "24-04-95"
}

###

POST http://localhost:5000/post
Content-Type: application/json

{
    "title": "my name is noam",
    "body": "im 25",
    "subject": "fuck you too",
    "date": "23-01-98"
}

###

POST http://localhost:5000/post
Content-Type: application/json

{
    "title": "my name is hello",
    "body": "im 542 y/o",
    "subject": "fuck 888",
    "date": "66565656"
}

###

POST http://localhost:5000/post
Content-Type: application/json

{
    "title": " hello my name is yoram",
    "body": "im 265 y/o",
    "subject": "lol you",
    "date": "24-45-95"
}

###

POST http://localhost:5000/post
Content-Type: application/json

{
    "title": " HElLo my name is pazit",
    "body": "im 55 y/o",
    "subject": "fuck you",
    "date": "11-12-95"
}

###

POST http://localhost:5000/post
Content-Type: application/json

{
    "title": "my hello is assaf",
    "body": "im navoth",
    "subject": "fuck you",
    "date": "24-04-95"
}

###

POST http://localhost:5000/post
Content-Type: application/json

{
    "title": "my name hello noam",
    "body": "im 28 y/o",
    "subject": "fuck you",
    "date": "24-04-95"
}

###

POST http://localhost:5000/post
Content-Type: application/json

{
    "title": "my hello is noam",
    "body": "im 28 y/o",
    "subject": "fuck you",
    "date": "24-04-95"
}

###

GET http://localhost:5000/post
Content-Type: application/json

{
"from": "dskd",
"to": "rr0",
"filterBy": "     HeLLo  "
}